# Project: Lab9C_Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = CardRunner.o
LINKOBJ  = CardRunner.o
LIBS     = -L"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/lib" -L"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/include" -I"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/matthew.hall/Desktop/C++/C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Lab9C_Project.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

CardRunner.o: CardRunner.cpp
	$(CPP) -c CardRunner.cpp -o CardRunner.o $(CXXFLAGS)
